add pokedex pages
kuanyshtokanov/startupjs_pokemon pull request #1
Opened 2021-03-29 14:00 UTC by kuanyshtokanov

2021-04-09 15:15 UTC, lupenq requested changes

2021-04-09 15:15 UTC, lupenq commented on components/Pagination/index.js
> +  console.log('count', count)
Давай уберем консольлоги лишние

2021-04-09 15:15 UTC, lupenq commented on components/Pagination/index.js
> +
Пустая строка

2021-04-09 15:15 UTC, lupenq commented on components/Pagination/index.js
> +  const [curPage, setPage] = useState()
const [currentPage, setCurrentPage] = useState()
вот так будет корректно

2021-04-09 15:15 UTC, lupenq commented on components/Pagination/index.styl
> +  flex-direction row
Компонент Row

2021-04-09 15:15 UTC, lupenq commented on components/PokemonCard/index.js
> +          Text.abilitiesTxt=abilities
А почему не Span?
и зачем сверху два дива?

2021-04-09 15:15 UTC, lupenq commented on components/PokemonCard/index.styl
> +  width 100%
Используем unit вместо px

2021-04-09 15:15 UTC, lupenq commented on components/PokemonCard/index.styl
> +    max-width calc(50% - 2u)
calc не работает на react-native

2021-04-09 15:15 UTC, lupenq commented on components/PokemonCard/index.styl
> +  flex-direction row
Row

2021-04-09 15:15 UTC, lupenq commented on components/PokemonCard/index.styl
> +  flex-direction row
Row

2021-04-09 15:15 UTC, lupenq commented on components/PokemonDetails/index.js
> +    emit('url', '/')
emit после del

2021-04-09 15:15 UTC, lupenq commented on components/PokemonDetails/index.js
> +    Card.wrapper(styleName=[{detailForm}])
от массива можно отказаться

2021-04-09 15:15 UTC, lupenq commented on components/PokemonDetails/index.js
> +                Tag.tag(styleName=[{first: index===0}] key=index style=({ backgroundColor: (POKEMON_TYPES.find(t=> t.name === type) || []).color })) #{type.toUpperCase()}
тут тоже

2021-04-09 15:15 UTC, lupenq commented on components/PokemonDetails/index.js
> +                Tag.tag(styleName=[{first: index===0}] key=index style=({ backgroundColor: (POKEMON_TYPES.find(t=> t.name === type) || []).color })) #{type.toUpperCase()}
и проп style давай в .styl файл перенесем

2021-04-09 15:15 UTC, lupenq commented on components/PokemonDetails/index.js
> +            Button.btn.last(
не надо два класса навешивать таким образом

2021-04-09 15:15 UTC, lupenq commented on components/PokemonDetails/index.styl
> +//   display flex
comments

2021-04-09 15:15 UTC, lupenq commented on components/PokemonFilter/index.js
> +      Tag(style=({backgroundColor: record.color})) #{record.label}
styleName

2021-04-09 15:15 UTC, lupenq commented on components/PokemonFilter/index.styl
> +  // max-width 600px
same

2021-04-09 15:15 UTC, lupenq commented on components/PokemonForm/index.js
> +        await model.set(`pokemons.${pokemon.id}`, formValues)
Используй хук useModel вместе model
https://startupjs-ui.dmapper.co/docs/tutorial/ShareDBHooks

2021-04-09 15:15 UTC, lupenq commented on components/PokemonForm/index.js
> +          inputStyle={
inputStyleName

2021-04-09 15:15 UTC, lupenq commented on main/pages/PHome/index.styl
> +  max-width 1024px
u

2021-04-15 12:43 UTC, kuanyshtokanov commented on components/PokemonForm/index.js
> +        await model.set(`pokemons.${pokemon.id}`, formValues)
не понял как использовать хук

2021-04-15 13:27 UTC, lupenq commented on components/PokemonForm/index.js
> +        await model.set(`pokemons.${pokemon.id}`, formValues)
const [pokemonData, $pokemonData] = useDoc('pokemons', pokemon.id)

$pokemonData.set(formValues)

2021-04-28 13:22 UTC, merged